rivian/delta-go

README.md, delta.go, delta_test.go, go.mod, internal/s3mock/s3mock.go, lock/dynamolock/dynamolock.go, lock/filelock/filelock.go, lock/filelock/filelock_test.go, lock/redislock/redislock.go, schema.go, state/dynamostate/dynamostate.go, state/dynamostate/dynamostate_test.go, state/filestate/filestate.go, state/filestate/filestate_test.go, state/redisstate/rediststate.go, state/redisstate/rediststate_test.go, storage/filestore/filestore.go, storage/filestore/filestore_test.go, storage/s3store/s3store.go, storage/s3store/s3store_test.go
gitlab.com/rivian/rel/delta-go references will not work in open source, need to be updated to open repo github.com/rivian/delta-go
=> Updated go mod to github.com/rivian/delta-go

action.go, action_test.go
The prior version was pushing the Create operationParameters as a dictionary, the expected values should be json.
old: `"operationParameters":{"mode":"Append","partitionBy":["date"], "predicate": null}`
new: `"operationParameters":{"mode":"Append","partitionBy":"[\"date\"]", "predicate": "[]"}`
In production, we were seeing this error:
```
java.util.concurrent.ExecutionException: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.String` from Array value (token `JsonToken.START_ARRAY`)
at [Source: (String)"{"commitInfo":{"clientVersion":"delta-go.alpha-0.0.0","isBlindAppend":true,"operation":"delta-go.Write","operationParameters":{"mode":"Append","partitionBy":["date"],"Predicate":""},"timestamp":1680899747050}}"; line: 1, column: 158] …
```
=> Updated Create.GetCommitInfo() to properly handel partitionBy json value

.gitignore, action.go, delta.go, internal/s3mock/s3mock.go, storage/filestore/filestore.go, storage/filestore/filestore_test.go, storage/s3store/s3store.go, storage/s3store/s3store_test.go, storage/storage.go
The S3 `List()` operation now accepts a continuation token to allow manual paging of results.
`ListAll()` will perform the paging internally and return all results.
I've left `List()` as public after all.  The `DeltaTable` `Exists()` function is using `List()` as a fallback to look for commit log files if version 0 doesn't exist, and it would be a waste of resources to list out everything in the _delta_log folder.
Thanks Rahul for the `ListAll()` implementation!  I restructured it slightly to match `List`.
=> List() in storage is now paged; ListAll() does paging for you

delta_test.go, lock/nillock/nillock.go, lock/nillock/nillock_test.go, state/localstate/localstate.go, state/localstate/localstate_test.go
- New lock and state for testing and scripting when we know that there are no concurrent writers:
- `NilLock` has no actual locking, it just returns true/nil
- `LocalStateStore` stores the version in memory, with no concurrency protection
- Example of using `NilLock` and `LocalStateStore` is in `TestTryCommitWithNilLockAndLocalState` in `delta_test.go`
=> Add nil lock and local statestore

README.md, action.go, action_test.go, checkpoint.go, checkpoint_test.go, delta.go, delta_test.go, tablestate.go
This splits the `Add` action into two variants, `Add` and `AddWithPartition`.  `Add` doesn't have the `PartitionValuesParsed` field.  Using this fixes the problem where we can't checkpoint without partitions, because `PartitionValuesParsed` would be an empty struct and parquet doesn't allow empty nested schemas.
Also we now return errors on `Create`, `OpenTable` and `OpenTableWithVersion` when the min reader or min writer version is greater than we support, although the operations still succeed.
Additional fixes:
- add json names for `_last_checkpoint` serialization/deserialization
- fix what is written to the `size` field in `_last_checkpoint` (I've also filed a bug in delta-rs)
- omit `parts` field from `_last_checkpoint` for single part checkpoints
=> Fix checkpointing without partitions, other checkpointing fixes

checkpoint.go, checkpoint_test.go, delta.go
- Added the checkpointing config option UnsafeIgnoreUnsupportedReaderWriterVersionErrors
- I also modified table.Create to return both reader/writer unsupported version errors if both are true
=> Config option to allow checkpointing with unsupported reader/writer versions

action.go, action_test.go
The DataSkippingReader in Spark requires the null count be set.
=> Set null counts to zero instead of leaving blank

logstore/dynamodblogstore/dynamodblogstore.go
- Use `Attribute` type for constants in `dynamodblogstore.go`.
=> fix: use Attribute type for constants in DynamoDB log store

.github/dependabot.yml, state/dynamostate/dynamostate.go, state/dynamostate/dynamostate_test.go
- Use the complete DynamoDB mock in `dynamostate` package.
- Remove the DynamoDB mock defined in `dynamostate_test.go`.
=> fix: use complete DynamoDB mock in dynamostate package

action.go, action_test.go, checkpoint_test.go, delta_test.go
Removed pointers in Add struct. Stats writes to commit.json as `"stats":""` now, before it wrote as `"stats":null`
Ran unit tests.
Local testing:
`spark version 3.4.1`
`pyspark --packages io.delta:delta-core_2.12:2.4.0 --conf "spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension" --conf "spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog"`
Tested with local spark read and TestCreateWithParquet where the commit was set manually with the add record `{"add":{"path":"part-d35f4fec-c372-43d7-ad35-383d17404d9c.snappy.parquet","partitionValues":{},"size":1708,"modificationTime":1694730396674,"dataChange":true,"stats":""}}`
```
>>> df = spark.read.format("delta").load("/var/folders/5p/bvr9gvdd57b51vzkvk8j346h0000gn/T/TestCreateWithParquet4200968178/001")
>>> …
```
=> Removed pointer on Add.Stats and Add.Tags

.github/workflows/push.yml, .gitignore, delta.go, delta_test.go, internal/s3utils/s3mock.go, storage/s3store/s3store_test.go
- Change the `DeltaTable.Exists()` function to recognize checkpoint files as well as commit files
- Use the list iterator when looking for commit/checkpoint files, so that if none are on the first page of results we will look through the entire log folder
- Add a pagination option to the S3 mock client for testing
- Expand unit test
I added a unit test specifically for this situation, `TestDeltaTableExistsManyTempFiles()`.  It fails without the changes to `Exists()` and passes with them.
=> Fix DeltaTable.Exists() - look for checkpoint files as well as commit files, and iterate the entire log folder

action.go, action_test.go, arrow.go, checkpoint.go, checkpoint_test.go, config.go, delta.go, delta_test.go, internal/dynamodbutils/dynamodbclient.go, internal/s3utils/s3mock.go, lock/dynamolock/dynamolock.go, lock/filelock/filelock.go, lock/filelock/filelock_test.go, lock/lock.go, lock/redislock/redislock.go, storage/filestore/filestore.go, storage/filestore/filestore_test.go, storage/s3store/s3store.go, storage/s3store/s3store_test.go, storage/storage.go, tablestate.go
Prefixes global error variables with "Err" instead of "Error." Both [Google](https://google.github.io/styleguide/go/best-practices#error-structure) and [Uber's](https://google.github.io/styleguide/go/best-practices#error-structure) style guides prefer this naming convention.
=> fix: prefix global error variables with "Err" instead of "Error"

.github/workflows/push.yml
Uses Redis version 6.x for build instead of specifying multiple Redis versions. Our workflows aren't compatible with the latest version.
=> ci: use Redis version 6.x for build

.github/workflows/push.yml, go.mod
Downgrades to Go version 1.20 to achieve Arrow compatibility.
=> fix: downgrade to Go version 1.20

delta.go, schema.go
Removes all instances of variables being named with snake case. Go prefers camel case over snake case.
=> fix: remove all instances of snake case

go.mod, go.sum, lock/dynamolock/dynamolock.go
Removes dependency on `aws-sdk-go`. We now only depend on `aws-sdk-go-v2`.
=> fix: remove dependency on aws-sdk-go

action.go, action_test.go, checkpoint.go, checkpoint_test.go, delta.go, delta_test.go, schema.go, tablestate.go
Many of the function and variable names in the `delta` package have the word "Delta" in them. Since these functions and variables are already scoped to the `delta` package, removing "Delta" from their names would improve clarity.
=> refactor!: simplify naming in delta package

README.md, checkpoint_test.go, delta.go, delta_test.go
Removes the parameters from `PrepareCommit()` and `Commit()` to simplify the API.
=> refactor!: remove the parameters from PrepareCommit() and Commit()

checkpoint.go, checkpoint_test.go, delta.go, delta_test.go
- Make `DoesCheckpointVersionExist()` public so we can use it elsewhere
- Clean up the commit and checkpoint regular expressions; the named groups weren't being used so I've removed them, plus they weren't checking start and end of string everywhere so they were overly permissive.
Expanded unit test cases
=> Make DoesCheckpointVersionExist() public

checkpoint.go, checkpoint_test.go, delta.go, ondiskstate_test.go, storage/filestore/filestore_test.go, storage/s3store/s3store.go, storage/s3store/s3store_test.go, tablestate.go
Checkpoint working folder will be automatically cleaned up (all contents will be deleted).  If it's created by a `LoadTable...` or `OpenTable...` operation that is not called by `CreateCheckpoint`, it will be cleaned up before those return.  If it's created for `CreateCheckpoint` it will be used for both the state read and checkpoint write, and cleaned up after.
To avoid unhappy mistakes, on-disk optimization will return an error if the working folder is not initially empty.
Also adds function `NewOptimizeCheckpointConfiguration()` to set the working folder automatically to `_delta_log/.tmp/checkpoint-v<version>-<random uuid>`
=> Working folder cleanup

checkpoint.go, checkpoint_test.go
We don't need the table, just the store
=> use store instead of table as parameter

ondiskstate.go
The `record.SetColumn()` function actually returns a new record, so the previous record needs a `Release()` call.
=> Release previous record when getting new record via SetColumn

delta.go
Adds a sleep between log store commit retries. Most of the errors in `tryCommitLogStore()` come from other writers committing concurrently. Adding a sleep will reduce writer contention.
=> fix: sleep between log store commit retries

delta.go
Since a version has been successfully committed even if acknowledgement fails, return the committed version when acknowledgement fails.
=> fix: return version if acknowledgement fails

delta.go, logstore/commitentry.go, logstore/dynamodblogstore/dynamodblogstore.go, logstore/dynamodblogstore/dynamodblogstore_test.go
- Errors out of `CommitLogStore()` if copying a temp file into a commit URI fails. Any operation performed after an uncompleted commit entry has been put in a log store shouldn't be retried; other writers can complete the commit entry.
- Improves descriptiveness of some info logs.
=> refactor: error out if a temp file copy fails

action_test.go, delta_test.go, schema.go, schema_test.go
Our existing code for converting to and from the JSON schema did not handle arrays, structs, or maps correctly.  The format has a union between strings and structs so I had to do a lot of manual parsing.
This functionality is currently used in checkpointing, so this should support checkpointing of tables with struct, array, and map columns. 
The schema strings in the unit test were copied from the initial commit log for delta tables created using pyspark.
=> Fix schema type handling when un/marshalling from/to JSON

checkpoint.go, delta.go
Fix for an issue that shows up in very specific circumstances: if there's an issue with the `_last_checkpoint` file and also the checkpoint has more than 1000 parts.
First, changed the `List` call to`ListAll` to get all checkpoint parts.
Second, if the check in `findLatestCheckpointsForVersion` for whether it's a complete checkpoint fails because there are parts missing or because there are filename issues, don't fail out - keep looking for another valid checkpoint instead.
=> Fix checkpoint parts count logic

go.mod, go.sum, storage/s3store/s3store.go
The call to Read() sometimes returns partial results so we need a loop.
=> Fix s3store ReadAt() function to handle Read() returning partial results

delta.go, logstore/commitentry.go
In `fixLog()`, if a temporary file's path is unable to be renamed to a commit URI, it can't be assumed that the failure was because the commit URI already exists; it's also possible that the renaming itself failed. I've improved the error handling so that `copyTempFile()` will be retried until either the commit URI exists or the maximum number of log fix attempts have been exhausted.
`Head()` and `copyTempFile()` in `fixLog()` are incorrectly taking absolute file paths as inputs -- I've modified their inputs so they receive relative paths instead. I've added `RelativeFilePath()` and `RelativeTempPath()` as methods of the `CommitEntry` struct to make fetching relative paths easier.
I've grouped some variable declarations to improve readability.
=> fix: improve error handling when copying a temporary file

delta_test.go
[We're seeing some log store unit tests fail intermittently.](https://github.com/rivian/delta-go/actions/runs/9572784012/job/26392890553) This is because copying temporary files into commit URIs can fail when writing commits concurrently; specifically, a temporary file may have been deleted by another writer after the other writer completed the commit. This isn't an issue, it just means other writers are responsible for completing transactions when copies fail. I've improved the handling of `CommitLogStore()` errors to ignore copy failure errors.
=> fix: improve the error handling in the log store unit tests
